name = "lean-nano-llvm"
version = "0.1.0"
defaultTargets = ["lean-nano-llvm"]

[[lean_lib]]
name = "LeanNanoLlvm"

[[lean_exe]]
name = "lean-nano-llvm"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.28.0"